### ISSUE TITLE
Create a day overview page of upcoming events to display on the screens.

### ISSUE THREAD

**Issue by RenedBruin** [Donders-Institute/calendar-web#2]
Room calendars.
Create a webpage which displays the upcoming events of the current day and in which room which events takes place at what time. 
This page updates regularly and removes events already past. Like airport flight info boards (arrival/departures)

**Comment by RenedBruin** [comment]
Example: In past from this info a html page was created which could be shown on the screens:
About 12/15 lines would fit on the screen

starttime /room/duration/titel

1531206000000 01153 7200000 DCCN MT
1531207800000 01154 3600000 OC meeting
1531207800000 FRIS 3600000 OC Meeting
1531207800000 KUTAS 5400000 CNS meeting "research commissie"
1531207800000 LURIA 3600000 dyncon group meeting
1531207800000 OOF 5400000 Affective Neuroscience
1531213200000 KUTAS 3600000 Group meeting Marquand
1531216800000 OOF 3600000 Brain Stimulation Meeting
1531218600000 FRIS 5400000 Cognitive Affective Neuroscience lab meeting
1531220400000 KUTAS 3600000 Lab meeting Mike Cohen/Ole Jensen
1531220400000 LURIA 5400000 NBL PhD meeting
1531222200000 OOF 5400000 MR Physics
1531227600000 KUTAS 7200000 DI-BV
1531227600000 OOF 7200000 Connectivity Seminar

**Comment by linusband** [comment]
Feature already exists
